Repository kubernetes-sigs/hierarchical-namespaces, pull requests merged in 2021-05, with the labels that each got.

#4 Minor tweaks to the readme
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#31 Fix e2e tests
  hack/prow-run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#34 Update docs for new repo
  CONTRIBUTING.md
  README.md
  RELEASE.md
  docs/_config.yml
  docs/code-of-conduct.md
  docs/contributing.md
  docs/user-guide/how-to.md
  hack/krew-kubectl-hns.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#35 Migrate items listed in .gitignore
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, size/M

#36 Replace excluded namespace label with included
  Makefile
  api/v1alpha2/hierarchy_types.go
  config/manager/manager.yaml
  config/webhook/webhook_patch.yaml
  internal/reconcilers/hierarchy_config.go
  internal/reconcilers/hierarchy_config_test.go
  internal/validators/namespace.go
  internal/validators/namespace_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#39 Add MWH and update VWH on included-namespace label
  cmd/manager/main.go
  config/webhook/manifests.yaml
  internal/mutators/namespace.go
  internal/mutators/namespace_test.go
  internal/mutators/setup.go
  internal/reconcilers/hierarchy_config.go
  internal/validators/anchor.go
  internal/validators/hierarchy.go
  internal/validators/hncconfig.go
  internal/validators/namespace.go
  internal/validators/namespace_test.go
  internal/validators/object.go
  internal/validators/setup.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#40 Update docs to add included-namespace label and deprecate excluded label
  docs/user-guide/concepts.md
  docs/user-guide/how-to.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#42 Add e2e tests for included-namespace label
  test/e2e/issues_test.go
  test/e2e/namespace_test.go
  test/e2e/wrong_included_namespace.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#43 Update validator message to point to included-namespace doc
  docs/user-guide/concepts.md
  internal/validators/namespace.go
Labels: approved, cncf-cla: yes, lgtm, size/S
