Repository kubernetes-sigs/hierarchical-namespaces, pull requests merged in 2021-07, with the labels that each got.

#45 Multi arch image builds
  .github/workflows/image.yaml
  Dockerfile
  Makefile
  config/default/manager_auth_proxy_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#54 Delete functions that are no longer used
  pkg/testutils/testutils.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/S

#52 Add presubmit to ensure make generate doesn't produce diffs
  Makefile
  hack/ci-test.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#57 Make error message for pre-submit check more clearly
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#56 Return non-zero code when pre-submit check fails
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#61 concepts.md: fix typo
  docs/user-guide/concepts.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#59 Allow HNC to propagate changes to CRD.
  .gitignore
  internal/reconcilers/object.go
  pkg/testutils/testutils.go
  test/e2e/issues_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L
