Repository kubernetes-sigs/hierarchical-namespaces, pull requests merged in 2022-02, with the labels that each got.

#111 Apple M1 support
  Makefile
  cloudbuild.yaml
  hack/krew-kubectl-hns.yaml
Labels: approved, cncf-cla: yes, ok-to-test, lgtm, size/M

#136 Use DynamicRESTMapper to lookup metadata from apiserver
  internal/apimeta/mapper.go
  internal/hncconfig/reconciler.go
  internal/hncconfig/reconciler_test.go
  internal/hncconfig/validator.go
  internal/hncconfig/validator_test.go
  internal/setup/reconcilers.go
Labels: approved, cncf-cla: yes, size/L, ok-to-test, lgtm

#145 Fix managed label conditions and docs
  api/v1alpha2/hierarchy_types.go
  docs/user-guide/concepts.md
  docs/user-guide/how-to.md
Labels: approved, cncf-cla: yes, size/L, lgtm
