Repository kubernetes-sigs/hierarchical-namespaces, pull requests merged in 2022-01, with the labels that each got.

#51 Deny requests adding tree labels
  internal/namespace/validator.go
  internal/namespace/validator_test.go
Labels: approved, cncf-cla: yes, ok-to-test, lgtm, size/M

#119 Simplify condition handling
  internal/forest/namespaceconditions.go
  internal/hierarchyconfig/reconciler.go
  internal/hierarchyconfig/validator.go
  internal/objects/reconciler.go
Labels: approved, cncf-cla: yes, size/L, lgtm

#121 Don't store external tree labels explicitly
  internal/forest/namespace.go
  internal/hierarchyconfig/reconciler.go
  internal/hierarchyconfig/validator_test.go
  internal/namespace/validator.go
  internal/namespace/validator_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#122 Initial implementation of managed labels
  api/v1alpha2/hierarchy_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  cmd/manager/main.go
  config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml
  internal/config/namespace.go
  internal/forest/namespace.go
  internal/hierarchyconfig/reconciler.go
  internal/hierarchyconfig/reconciler_test.go
  internal/integtest/helpers.go
Labels: approved, cncf-cla: yes, size/L, lgtm

#124 Validate anchor names are RFC 1123 labels
  internal/anchor/validator.go
  internal/anchor/validator_test.go
Labels: size/XS, approved, cncf-cla: yes, lgtm

#127 Fix timeout stopping testEnv api-server on K8s 1.20+
  internal/integtest/setup.go
Labels: size/S, approved, cncf-cla: yes, ok-to-test, lgtm

#125 Add per-object-level filtering based on labels (excluding Rancher-generated resources)
  docs/user-guide/concepts.md
  internal/integtest/helpers.go
  internal/objects/reconciler_test.go
  internal/selectors/selectors.go
Labels: approved, cncf-cla: yes, ok-to-test, lgtm, size/M

#129 Refactor main() into smaller bits
  cmd/manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#132 Improve webhooks deny invalid fields
  internal/anchor/validator.go
  internal/hierarchyconfig/validator.go
  internal/hncconfig/validator.go
  internal/webhooks/webhooks.go
Labels: approved, cncf-cla: yes, size/L, ok-to-test, lgtm

#126 Protect all labels and annotations on propagated objects
  internal/objects/validator.go
  internal/objects/validator_test.go
Labels: approved, cncf-cla: yes, ok-to-test, lgtm, size/M

#134 Add validation of managed labels/annotations
  internal/hierarchyconfig/validator.go
  internal/hierarchyconfig/validator_test.go
Labels: approved, cncf-cla: yes, size/L, ok-to-test, lgtm
