Repository kubernetes-sigs/hierarchical-namespaces, pull requests merged in 2022-04, with the labels that each got.

#178 Update readme after v1.0 release
  README.md
Labels: size/XS, approved, cncf-cla: yes, lgtm

#153 Introduce manager caching of Unstructured
  cmd/manager/main.go
  internal/config/cache_unstructured.go
  internal/integtest/setup.go
Labels: approved, cncf-cla: yes, ok-to-test, lgtm, size/M

#166 Cloudbuilds for each push to main branch
  .github/workflows/image.yaml
  README.md
  cloudbuild-build.yaml
  cloudbuild.yaml
  docs/automated-builds.md
Labels: approved, cncf-cla: yes, size/L, lgtm

#168 Validate subnamespace anchors on update
  config/webhook/manifests.yaml
  internal/anchor/validator.go
Labels: size/XS, approved, cncf-cla: yes, ok-to-test, lgtm

#194 Validate subnamespace anchors on update (backporting to v1.0 branch)
  config/webhook/manifests.yaml
  internal/anchor/validator.go
Labels: size/XS, approved, cncf-cla: yes, ok-to-test, lgtm

#183 Import HRQ into HNC (disabled by default)
  Makefile
  api/v1alpha2/hierarchicalresourcequota_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  cmd/manager/main.go
  config/crd/bases/hnc.x-k8s.io_hierarchicalresourcequotas.yaml
  config/crd/kustomization.yaml
  config/rbac/role.yaml
  config/variants/hrq/README
  config/variants/hrq/kustomization.yaml
  config/variants/hrq/webhook_patch.yaml
  internal/forest/forest.go
  internal/forest/namespace.go
  internal/forest/namespacehrq.go
  internal/forest/namespacehrq_test.go
  internal/hrq/hrqreconciler.go
  internal/hrq/hrqreconciler_test.go
  internal/hrq/hrqvalidator.go
  internal/hrq/hrqvalidator_test.go
  internal/hrq/rqreconciler.go
  internal/hrq/rqreconciler_test.go
  internal/hrq/rqstatusvalidator.go
  internal/hrq/rqstatusvalidator_test.go
  internal/hrq/utils/resources.go
  internal/hrq/utils/resources_test.go
  internal/integtest/setup.go
  internal/metadata/metav1.go
  internal/setup/reconcilers.go
  internal/setup/webhooks.go
  test/e2e/delete_crd_test.go
  test/e2e/hrq_test.go
Labels: approved, size/XXL, cncf-cla: yes, lgtm

#196 Disable HRQ e2e tests
  test/e2e/hrq_test.go
Labels: size/XS, approved, cncf-cla: yes, lgtm

#197 Use in-tree metav1.Condition instead of custom copied type
  api/v1alpha2/hierarchy_types.go
  api/v1alpha2/hnc_config.go
  api/v1alpha2/zz_generated.deepcopy.go
  internal/forest/namespace.go
  internal/forest/namespaceconditions.go
  internal/hncconfig/reconciler.go
  internal/kubectl/describe.go
  internal/objects/reconciler.go
  internal/selectors/selectors.go
Labels: approved, cncf-cla: yes, size/L, ok-to-test, lgtm

#187 Add security context
  config/manager/manager.yaml
Labels: size/S, approved, cncf-cla: yes, ok-to-test, lgtm

#202 Fix manifest kustomization for metrics service
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manager/metrics_service.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#205 Remove obsolete validation TODOs
  internal/anchor/validator.go
  internal/hierarchyconfig/validator.go
  internal/hncconfig/validator.go
  internal/namespace/validator.go
Labels: size/S, approved, cncf-cla: yes, lgtm

#203 Refactor adding/removing/contains finalizers
  internal/anchor/reconciler.go
  internal/hierarchyconfig/reconciler.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#207 Fix manifest kustomization for metrics service
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manager/metrics_service.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#206 Read-only client in webhooks only mode
  cmd/manager/main.go
  internal/anchor/reconciler.go
  internal/config/cache_unstructured.go
  internal/config/client.go
  internal/hierarchyconfig/reconciler.go
  internal/hncconfig/reconciler.go
  internal/integtest/setup.go
  internal/setup/reconcilers.go
Labels: approved, cncf-cla: yes, size/L, lgtm
