Repository kubernetes-sigs/hierarchical-namespaces, pull requests merged in 2022-03, with the labels that each got.

#139 Add liveness and startup/readiness probes
  cmd/manager/main.go
  config/manager/manager.yaml
Labels: kind/feature, approved, cncf-cla: yes, ok-to-test, lgtm, size/M

#137 Refactor webhook deny responses (cont)
  api/v1alpha2/groupversion_info.go
  internal/anchor/validator.go
  internal/hierarchyconfig/validator.go
  internal/hierarchyconfig/validator_test.go
  internal/hncconfig/validator.go
  internal/namespace/mutator.go
  internal/namespace/validator.go
  internal/objects/validator.go
  internal/webhooks/webhooks.go
Labels: approved, cncf-cla: yes, size/L, ok-to-test, lgtm

#156 change error message for check-fmt
  Makefile
Labels: size/XS, approved, cncf-cla: yes, ok-to-test, lgtm

#160 Fix probes when installing on a fresh cluster
  cmd/manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#161 Install Kind via 'go install'
  hack/prow-run-e2e.sh
Labels: size/XS, approved, cncf-cla: yes, lgtm

#155 Remove last callers of webhooks.Deny function and delete it
  internal/objects/validator.go
  internal/webhooks/webhooks.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#149 Copy labels and annotations from SubnamespaceAnchor to child namespace
  api/v1alpha2/subnamespace_anchor.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/hnc.x-k8s.io_subnamespaceanchors.yaml
  internal/anchor/reconciler_test.go
  internal/anchor/validator.go
  internal/anchor/validator_test.go
  internal/config/validator.go
  internal/hierarchyconfig/reconciler.go
  internal/hierarchyconfig/validator.go
  internal/integtest/helpers.go
Labels: approved, cncf-cla: yes, size/L, ok-to-test, lgtm

#165 Update docs for v1.0
  README.md
  docs/user-guide/README.md
  docs/user-guide/concepts.md
  docs/user-guide/faq.md
  docs/user-guide/how-to.md
Labels: approved, cncf-cla: yes, size/L, lgtm

#167 Introduce manifest variants
  Makefile
  cloudbuild.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_prometheus_metrics_patch.yaml
  config/default/manager_webhook_patch.yaml
  config/manager/manager.yaml
  config/variants/default-cc/README
  config/variants/default-cc/kustomization.yaml
  config/variants/default-cm/README
  config/variants/default-cm/kustomization.yaml
  config/variants/default-cm/webhookcainjection_patch.yaml
  config/variants/ha-webhooks-cc/README
  config/variants/ha-webhooks-cc/kustomization.yaml
  config/variants/nowebhooks-cc/README
  config/variants/nowebhooks-cc/kustomization.yaml
  hack/Makefile
  hack/prow-run-e2e.sh
Labels: size/XL, approved, cncf-cla: yes, lgtm

#171 Add readiness probe
  config/manager/manager.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm

#173 Add readiness probe
  config/manager/manager.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm

#176 Fix cert-manager build error
  config/certmanager/certificate.yaml
  config/crd/patches/cainjection_in_hierarchies.yaml
  config/variants/default-cm/README
Labels: size/S, approved, cncf-cla: yes, lgtm

#177 Fix cert-manager build error (cherry-pick)
  config/certmanager/certificate.yaml
  config/crd/patches/cainjection_in_hierarchies.yaml
  config/variants/default-cm/README
Labels: size/S, approved, cncf-cla: yes, lgtm
