Repository kubernetes-sigs/hierarchical-namespaces, pull requests merged in 2023-02, with the labels that each got.

#251 Resource config removed log continues to be output
  internal/hncconfig/reconciler.go
Labels: size/XS, approved, cncf-cla: yes, ok-to-test, lgtm

#254 Do not propagate Helm release Secrets
  docs/user-guide/concepts.md
  internal/integtest/helpers.go
  internal/objects/reconciler_test.go
  internal/selectors/selectors.go
Labels: kind/feature, approved, kind/documentation, cncf-cla: yes, ok-to-test, lgtm, size/M

#243 fix(concepts): fix the link for the resource quotas restriction example
  docs/user-guide/concepts.md
Labels: size/XS, approved, kind/documentation, cncf-cla: yes, ok-to-test, lgtm

#240 Add periodic HRQ resync
  cmd/manager/main.go
  internal/forest/namespacehrq.go
  internal/hrq/hrqreconciler_test.go
  internal/integtest/setup.go
  internal/setup/reconcilers.go
Labels: approved, cncf-cla: yes, size/L, lgtm

#260 Remove useless lines related to unit test
  docs/contributing.md
Labels: size/XS, approved, kind/documentation, cncf-cla: yes, ok-to-test, lgtm

#258 build(arm64): publish built binaries for linux/arm64
  cloudbuild.yaml
Labels: size/S, approved, cncf-cla: yes, ok-to-test, lgtm

#261 Update Dockerfile to Go 1.20
  Dockerfile
Labels: size/XS, approved, cncf-cla: yes, ok-to-test, lgtm

#262 Add Linux arm64 to Krew
  hack/krew-kubectl-hns.yaml
Labels: size/S, approved, cncf-cla: yes, lgtm

#263 Update docs for v1.1
  README.md
  docs/releasing.md
  docs/user-guide/README.md
  docs/user-guide/concepts.md
  docs/user-guide/how-to.md
  docs/user-guide/quickstart.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#266 Fix Go version [master]
  cloudbuild.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm

#265 Fix Go version [v1.1]
  cloudbuild.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm

#267 Update releasing docs
  docs/releasing.md
Labels: size/XS, approved, cncf-cla: yes, lgtm

#268 Upload HRQ and cert-manager manifests [v1.1]
  cloudbuild.yaml
Labels: size/S, approved, cncf-cla: yes, lgtm

#269 Upload HRQ and cert-manager manifests [master]
  cloudbuild.yaml
Labels: size/S, approved, cncf-cla: yes, lgtm
