Repository kubernetes-sigs/hierarchical-namespaces, pull requests merged in 2023-10, with the labels that each got.

#337 Fixed misleading delete logs. see issue #334
  internal/objects/reconciler.go
Labels: size/XS, approved, cncf-cla: yes, ok-to-test, lgtm

#333 Update mentions of testgrid dashboard link
  README.md
Labels: size/XS, approved, cncf-cla: yes, ok-to-test, lgtm

#304 Update docs for v1.1
  README.md
  docs/releasing.md
  docs/user-guide/README.md
  docs/user-guide/how-to.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#315 docs: improve grammar and simplify HRQ examples
  docs/user-guide/concepts.md
  docs/user-guide/quickstart.md
Labels: approved, needs-ok-to-test, cncf-cla: yes, lgtm, size/M

#340 Add annotation about ResourceQuota for HRQ implementation to some documents
  docs/user-guide/concepts.md
  docs/user-guide/how-to.md
  docs/user-guide/quickstart.md
Labels: approved, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm, size/M

#302 Fix Quickstart Document about allowCascadingDeletion
  docs/user-guide/quickstart.md
Labels: kind/bug, approved, kind/documentation, cncf-cla: yes, lgtm, size/M

#316 docs: apply k8s style guide to HRQ quickstart example
  docs/user-guide/quickstart.md
Labels: approved, cncf-cla: yes, ok-to-test, lgtm, size/M

#311 kubectl-hns: Add "delete" command
  docs/user-guide/how-to.md
  docs/user-guide/quickstart.md
  internal/kubectl/delete.go
  internal/kubectl/root.go
  test/e2e/quickstart_test.go
Labels: approved, cncf-cla: yes, size/L, ok-to-test, lgtm
