Repository kubernetes-sigs/hierarchical-namespaces, pull requests merged in 2024-03, with the labels that each got.

#348 Add default for the --namespace when it is not specify.
  internal/kubectl/create.go
  internal/kubectl/delete.go
  internal/kubectl/root.go
Labels: size/S, approved, cncf-cla: yes, ok-to-test, lgtm

#359 Use dependabot to update go modules
  .github/dependabot.yml
Labels: size/XS, approved, cncf-cla: yes, ok-to-test, lgtm

#351 Use GVK to validate resource type
  internal/hncconfig/reconciler.go
  internal/hncconfig/reconciler_test.go
  internal/hncconfig/validator.go
  internal/hncconfig/validator_test.go
Labels: approved, cncf-cla: yes, size/L, ok-to-test, lgtm

#354 Helm Chart for HNC installation
  Makefile
  charts/hnc/.helmignore
  charts/hnc/Chart.yaml
  charts/hnc/crds/hierarchicalresourcequotas.hnc.x-k8s.io.yaml
  charts/hnc/crds/hierarchyconfigurations.hnc.x-k8s.io.yaml
  charts/hnc/crds/hncconfigurations.hnc.x-k8s.io.yaml
  charts/hnc/crds/subnamespaceanchors.hnc.x-k8s.io.yaml
  charts/hnc/templates/NOTES.txt
  charts/hnc/templates/_helpers.tpl
  charts/hnc/templates/hnc-admin-role.yaml
  charts/hnc/templates/hnc-controller-manager-ha.yaml
  charts/hnc/templates/hnc-controller-manager-metrics-service.yaml
  charts/hnc/templates/hnc-controller-manager.yaml
  charts/hnc/templates/hnc-leader-election-role.yaml
  charts/hnc/templates/hnc-leader-election-rolebinding.yaml
  charts/hnc/templates/hnc-manager-role.yaml
  charts/hnc/templates/hnc-manager-rolebinding.yaml
  charts/hnc/templates/hnc-mutating-webhook-configuration.yaml
  charts/hnc/templates/hnc-validating-webhook-configuration.yaml
  charts/hnc/templates/hnc-webhook-server-cert.yaml
  charts/hnc/templates/hnc-webhook-service.yaml
  charts/hnc/values.yaml
  docs/user-guide/how-to.md
  hack/helm_patches/NOTES.txt
  hack/helm_patches/_helpers.tpl
  hack/helm_patches/update-helm.sh
Labels: kind/feature, approved, size/XXL, cncf-cla: yes, ok-to-test, lgtm
